/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "sort.h"


void
cantor_1(char *host)
{
	CLIENT *clnt;
	intarr  *sorted;
	intarr  unsorted;

#ifndef	DEBUG
	clnt = clnt_create (host, Cantor, sort, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
        int i; int z;
        printf("\n enter number of elements: ");
        scanf("%d",&unsorted.intarr_len);
        unsorted.intarr_val = (int *) malloc(sizeof(int) *       unsorted.intarr_len);
        for(i=0; i < unsorted.intarr_len; i++){
            printf("\n enter element %d: ",i+1);
            scanf("%d",&z);
            unsorted.intarr_val[i] = z;
        }
	sorted = sortlinkedlist_1(&unsorted, clnt);
    for(i=0; i < sorted->intarr_len; i++){
        printf("\n %d",sorted->intarr_val[i]);
    }
    printf("\n");

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	cantor_1 (host);
exit (0);
}
