/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SORT_H_RPCGEN
#define _SORT_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


typedef struct {
	u_int intarr_len;
	int *intarr_val;
} intarr;

#define Cantor 0x1234
#define sort 1

#if defined(__STDC__) || defined(__cplusplus)
#define SortLinkedList 1
extern  intarr * sortlinkedlist_1(intarr *, CLIENT *);
extern  intarr * sortlinkedlist_1_svc(intarr *, struct svc_req *);
extern int cantor_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SortLinkedList 1
extern  intarr * sortlinkedlist_1();
extern  intarr * sortlinkedlist_1_svc();
extern int cantor_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_intarr (XDR *, intarr*);

#else /* K&R C */
extern bool_t xdr_intarr ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SORT_H_RPCGEN */
