/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "sort.h"

intarr *
sortlinkedlist_1_svc(intarr *unsorted, struct svc_req *rqstp)
{
	static intarr  sorted;
    sorted.intarr_len = unsorted->intarr_len;
    sorted.intarr_val = unsorted->intarr_val;
    int i,j; int temp, max=0;

    for(i=0; i < sorted.intarr_len; i++){
        max = sorted.intarr_val[i];
        for(j=0; j <sorted.intarr_len; j++){
            if (sorted.intarr_val[j] > max){
                temp = sorted.intarr_val[i];
                sorted.intarr_val[i] = sorted.intarr_val[j];
                sorted.intarr_val[j] = temp;
            }
        }
    }
	return &sorted;
}
