/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "sort.h"

bool_t
xdr_intarr (XDR *xdrs, intarr *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->intarr_val, (u_int *) &objp->intarr_len, ~0,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}
